pipeline:
  name: my-app
  identifier: myapp
  projectIdentifier: Temperory
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: python-flask-blog
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Building image
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: docker build -t my-app .
              - step:
                  type: Run
                  name: tagging docker file
                  identifier: tagging_docker_file
                  spec:
                    shell: Sh
                    command: docker tag my-app yourusername/my-app
        delegateSelectors:
          - ec2-medium
